import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api, authHeaders } from '../services/api'

type CaseloadItem = { id:number; name:string; email:string; completed_assessments:number; latest_session_id:number|null; latest_completed_at:string|null; review_cues:string[]; telemetry_samples:number }
const date = (value:string|null) => value ? new Date(value).toLocaleDateString() : 'No completed session'

export function CounsellorDashboardPage() {
  const [items, setItems] = useState<CaseloadItem[]>([]); const [query, setQuery] = useState(''); const [onlyReview, setOnlyReview] = useState(false); const [error, setError] = useState<string|null>(null)
  useEffect(() => { api.get<CaseloadItem[]>('/counsellor/overview', { headers: authHeaders() }).then(r => setItems(r.data)).catch(() => setError('Unable to load the counsellor caseload.')) }, [])
  const shown = useMemo(() => items.filter(item => (!onlyReview || item.review_cues.length) && `${item.name} ${item.email}`.toLowerCase().includes(query.toLowerCase())), [items, onlyReview, query])
  const reviewCount = items.filter(item => item.review_cues.length).length
  return <section className="space-y-7">
    <div className="rounded-2xl bg-slate-950 px-6 py-8 text-white shadow-lg sm:px-9"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-300">Counsellor workspace</p><h1 className="mt-3 text-3xl font-bold">See the whole caseload, then focus your review.</h1><p className="mt-3 max-w-2xl text-slate-300">Review cues highlight missing or unusual session observations. They are prompts for conversation—not clinical findings or risk determinations.</p></div>
    {error && <p className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-700">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-3"><Stat label="Students assessed" value={items.length}/><Stat label="Completed reports" value={items.reduce((n, i) => n + i.completed_assessments, 0)}/><Stat label="Needs review" value={reviewCount} accent="amber"/></div>
    <div className="grid gap-5 lg:grid-cols-5"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-3"><div className="flex items-baseline justify-between"><div><h2 className="font-bold text-slate-900">Assessment activity</h2><p className="mt-1 text-sm text-slate-500">Completed reports by student</p></div><span className="text-xs font-medium text-slate-500">Caseload comparison</span></div><div className="mt-5 space-y-3">{[...items].sort((a,b)=>b.completed_assessments-a.completed_assessments).slice(0,5).map(item=><div key={item.id} className="grid grid-cols-[8rem_1fr_2rem] items-center gap-3 text-sm"><span className="truncate font-medium text-slate-700">{item.name}</span><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-600" style={{width:`${Math.max(8,(item.completed_assessments/Math.max(1,...items.map(i=>i.completed_assessments)))*100)}%`}}/></div><span className="text-right font-semibold text-slate-700">{item.completed_assessments}</span></div>)}{!items.length&&<p className="py-4 text-sm text-slate-500">Assessment activity will appear here.</p>}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm lg:col-span-2"><h2 className="font-bold text-slate-900">Data coverage</h2><p className="mt-1 text-sm text-slate-500">Latest completed session only</p><div className="mt-6 grid place-items-center"><div className="grid h-32 w-32 place-items-center rounded-full" style={{background:`conic-gradient(#4f46e5 ${(items.filter(i=>i.telemetry_samples>0).length/Math.max(1,items.length))*360}deg,#e2e8f0 0deg)`}}><div className="grid h-24 w-24 place-items-center rounded-full bg-white text-center"><span className="text-2xl font-bold text-slate-900">{items.filter(i=>i.telemetry_samples>0).length}</span><span className="text-xs text-slate-500">with CV data</span></div></div></div><p className="mt-5 text-center text-xs text-slate-500">CV data supports session context; it is optional and non-diagnostic.</p></div></div>
    {reviewCount>0&&<div className="rounded-2xl border border-amber-200 bg-amber-50/70 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-amber-800">Priority review queue</p><h2 className="mt-1 text-xl font-bold text-slate-900">{reviewCount} student{reviewCount===1?'':'s'} have a review cue</h2><p className="mt-1 text-sm text-slate-700">Use these cues to choose where to look next—not to infer a diagnosis.</p></div><button onClick={()=>setOnlyReview(true)} className="rounded-lg bg-amber-400 px-4 py-2 font-semibold text-slate-950">View review queue</button></div></div>}
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><h2 className="text-xl font-bold text-slate-900">Caseload overview</h2><p className="text-sm text-slate-500">Open a full student history or jump directly to their latest report.</p></div><div className="flex gap-2"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search student" className="rounded-lg border border-slate-300 px-3 py-2 text-sm"/><button onClick={()=>setOnlyReview(v=>!v)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${onlyReview?'bg-amber-400 text-slate-950':'border border-slate-300 text-slate-700'}`}>{onlyReview?'Showing review cues':'Review cues only'}</button></div></div>
      <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-y bg-slate-50 text-slate-500"><tr><th className="p-3">Student</th><th className="p-3">Latest report</th><th className="p-3">Session quality</th><th className="p-3">Review cues</th><th className="p-3"></th></tr></thead><tbody>{shown.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-3"><p className="font-semibold text-slate-900">{item.name}</p><p className="text-slate-500">{item.email}</p></td><td className="p-3">{date(item.latest_completed_at)}<p className="text-xs text-slate-500">{item.completed_assessments} completed</p></td><td className="p-3">{item.telemetry_samples ? `${item.telemetry_samples} CV samples` : 'No CV samples'}</td><td className="p-3">{item.review_cues.length ? <div className="flex flex-wrap gap-1">{item.review_cues.map(c=><span key={c} className="rounded-full bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800">{c}</span>)}</div> : <span className="text-emerald-700">No review cue</span>}</td><td className="p-3 text-right"><div className="flex justify-end gap-2"><Link className="text-indigo-700 underline" to={`/counsellor/students/${item.id}`}>History</Link>{item.latest_session_id && <Link className="rounded-md bg-indigo-700 px-3 py-2 font-semibold text-white" to={`/counsellor/sessions/${item.latest_session_id}`}>Open report</Link>}</div></td></tr>)}</tbody></table>{!shown.length && <p className="p-8 text-center text-slate-500">No students match these filters.</p>}</div></div>
  </section>
}
function Stat({label,value,accent}:{label:string;value:number;accent?:'amber'}) { return <div className={`rounded-2xl border p-5 shadow-sm ${accent?'border-amber-200 bg-amber-50':'border-slate-200 bg-white'}`}><p className="text-sm text-slate-500">{label}</p><p className={`mt-1 text-3xl font-bold ${accent?'text-amber-700':'text-indigo-700'}`}>{value}</p></div> }
